### ISSUE TITLE
Username enhancement

### ISSUE THREAD

**Issue by ghost** [xTACTIXzZ/Hydrazine#1]
```
public static String generateUsername() {
	String[] chars = 
"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_".split("");
	StringBuilder result = new StringBuilder();
	for(int i = 0; i < 3+(int)(Math.random()*14); i++) 
		result.append(chars[(int)(Math.random()*chars.length)]);
	return result.toString();
}
```
Ich würde das benutzen, anstatt eine ganze Klasse.
Die Funktion ist nicht gerade performant, aber sie zeigt wie man das "Namen Problem" lösen könnte, ohne ~145 Zeilen Code.

**Comment by stenocyb** [comment]
Okay, ich werde deine Methode übernehmen, danke für deinen Beitrag!

**Comment by ghost** [comment]
Schön, dass du verstanden hast was ich meine ;)

**Comment by stenocyb** [comment]
Ich werde allerdings nicht die ganze Klasse ersetzen sondern nur die methode, die zufällige Namen generiert.
