### ISSUE TITLE
Multiple Accounts/Proxies?

### ISSUE THREAD

**Issue by KzoeMC** [xTACTIXzZ/Hydrazine#11]
Can you type out the correct format to have multiple accounts join at the same time? the same with using multiple proxies at the same time? I'm having trouble figuring out how to do so.

**Comment by stenocyb** [comment]
You can use multiple accounts in multiple ways.

If you want to connect to a premium server, you have to use the **pflood** module. This module has to be configured beforehand by appending the '-c' switch. By configuring the module, you can choose a file that contains minecraft account credentials for your bots. Each line of the file has to be in this format: _username/email:password_.

_**Example:**_ `java -jar Hydrazine.jar -m pflood -h server.net -sp socksproxies.txt -ap authproxies.txt`
_**Explanation:**_ This command will send the preconfigured amount of bots to the server 'server.net' and each bot will log in using an authentication proxy from the file authproxies.txt and then join the server using a **socks5** proxy from the file socksproxies.txt.

For cracked servers, you can use the **cflood** module. You can either configure this module (by appending the '-c' switch to the command) to load usernames from a file or you may choose to use the '-gu' (generate usernames) switch to automatically generate usernames.

_**Example:**_ `java -jar Hydrazine.jar -m cflood -h server.net -sp socksproxies.txt -gu random`
_**Explanation:**_ This command will send the preconfigured amount of bots to the server 'server.net', generating random usernames for the bots and using a socks5 proxy from the file socksproxies.txt for each bot.
