### ISSUE TITLE
Ran into a problem while getting bots.

### ISSUE THREAD

**Issue by Stick223** [xTACTIXzZ/Hydrazine#15]
When I run the module "pflood" It reads: ">This module hasn't been configured yet. Would you like to do so now? [Yes/No]: "
Then shortly after that it asks for the path to the file containing minecraft account credentials, which I have no idea where to find. Where can I find this?

**Comment by stenocyb** [comment]
You need to have a list of minecraft premium accounts inside of a file, separated by line. (format: email/user:password)

For example:
```
steveminecraft@email.com:p4ssw0rd
abccraft@cmail.com:w0rdl1st
```

Then, you can enter the path to that file and the program will load the accounts automatically.

Note: if you have no premium account(s), check out the 'cflood' module, it works with cracked accounts/servers.
