### ISSUE TITLE
It doesn't exit

### ISSUE THREAD

**Issue by TheGameSpider** [xTACTIXzZ/Hydrazine#4]
Hello,
Hydrazine is an awesome app to create bots (using cclient) to keep my minecarft farms loaded. The problem is, when the bot is kicked from the server, it won't stop/exit so it cannot be restarted automatically using a .sh script. It would be nice if the app exits when the user is disconnected.

**Comment by stenocyb** [comment]
Thank you for informing me about this problem, it should be fixed now. :)
