### ISSUE TITLE
functions

### ISSUE THREAD

**Issue by CrismaruIlie** [xTACTIXzZ/Hydrazine#7]
Can you add the function ping before connecting and all types of proxy please ?

**Comment by stenocyb** [comment]
Yup, working on it :)

**Comment by stenocyb** [comment]
I added the 'proxychecker' module, you can check whether your proxies are working with this module. However, this process is quite slow, if you have a big list of proxies it would be better to use online services that check your proxies for you. It should be noted that Hydrazine does only work with **socks5** proxies (-sp) and **https** proxies (-ap).
